baseURL = 'https://tl-mechs.com/'
languageCode = 'en-us'
title = 'TL Mechs Guide'
theme = 'hugo-book'

[params]
  BookToC = true
  BookMenuBundle = '/menu'
  # Theme options: 'light', 'dark', or 'auto' (follows system preference)
  BookTheme = 'auto'
